### ISSUE TITLE
Floris Blockage models

### ISSUE THREAD

**Issue by Ooussamaa** [NREL/floris#616] opened 2023-03-30 14:30 UTC
### Discussed in https://github.com/NREL/floris/discussions/615

<div type='discussions-op-text'>

<sup>Originally posted by **Ooussamaa** March 30, 2023</sup>
Hey guys, I have a specific question for you 
Now I can see that wake models exist in Floris and I know how to activate them, but blockage models I they exist but my question is: they are already coupled with blockage models so the AEP I calculate takes into account Wake and blockage effects at the same time or wake only ? and if it was the case, can you please push me in the right direction to find how to activate them coz I have searched in the litterature and I could not find my answer.
My purpose is: calculate the AEP for a wind farm by taking into account blockage and wake at the same time !

Thank you</div>

**Comment by rafmudaf** [comment] 2023-03-30 15:08
@Ooussamaa I'm closing this issue since the same question is posed in a couple of other places (#615 and https://github.com/NREL/floris/discussions/614#discussioncomment-5475945).

**Closed by rafmudaf** 2023-03-30 15:08 UTC

**Comment by kilojoules** [comment] 2023-04-05 12:09
This paper discusses some capabilities of modeling blockage in FLORIS: https://www.nrel.gov/docs/fy20osti/76855.pdf. It is not clear to me how these results can be reproduced. Is there an example available regarding how to model blockage in FLORIS?

**Comment by ebranlard** [comment] 2023-04-20 16:05
Hi, 

The repository used for the FLORIS with blockage effect  (https://www.nrel.gov/docs/fy20osti/76855.pdf), contains the source code and some usgae examples:
   https://github.com/ebranlard/wiz 

Unfortunatley, this  was not updated for a while and is therefore using an older version of FLORIS.

**Comment by prith-gs** [comment] 2023-11-29 06:46
Hello, 

Are there any plans to add blockage models to the recent version of FLORIS (v3.5 and above)?
