### ISSUE TITLE
v4 Power of most upstream turbine doesn't change for change in yaw angle < ~15degrees

### ISSUE THREAD

**Issue by achenry** [NREL/floris#798] opened 2024-02-08 23:18 UTC
The power of the upstream turbine does not seem to be sensitive to yaw angle in the expected way. In particular, running
```
import numpy as np
from floris.tools import FlorisInterface
 
fi = FlorisInterface("inputs/gch.yaml")
fi.reinitialize(
    wind_speeds=[8.0],
    wind_directions=[270.0],
    layout_x=[0, 1000, 2000],
    layout_y=[0, 0, 0]
)
 
yaw_angles_1 = np.array([[0., 0., 0.]])
fi.calculate_wake(yaw_angles=yaw_angles_1)
power_1 = fi.get_turbine_powers() / 1e3
print(power_1)
 
yaw_angles_2 = np.array([[5., 0., 0.]])
fi.calculate_wake(yaw_angles=yaw_angles_2)
power_2 = fi.get_turbine_powers() / 1e3
 
yaw_angles_3 = np.array([[15., 0., 0.]])
fi.calculate_wake(yaw_angles=yaw_angles_3)
power_3 = fi.get_turbine_powers() / 1e3
 
print("T0 yaw angle 0 deg:", power_1)
print("T0 yaw angle 5 deg:", power_2)
print("T0 yaw angle 15 deg:", power_3)
```
produces the same power for T0 whether the yaw angle is 0 or 5 degrees. However, the power is reduced for 15 degrees. 

## Expected behavior

T0 power is highest with 0 yaw angle, somewhat lower with 5 degree yaw angle, and lowest with 15 degree yaw angle.

**Comment by misi9170** [comment] 2024-02-08 23:22
This appears to affect thrust as well, as the downstream turbines' powers are also not changing.

**Comment by misi9170** [comment] 2024-02-08 23:27
Hang on; I think this was my mistake---I think I had incorrectly assigned the angles---double checking, but this may not be an issue

**Comment by misi9170** [comment] 2024-02-08 23:37
Ok, sorry @achenry, I misunderstood when we spoke (and then gave you bad test code)! This runs as expected and is not a bug; I'm going to close this issue.

**Closed by misi9170** 2024-02-08 23:37 UTC
Labels: v4
